-- Q.1 WRITE A QUERY THAT LISTS EACH ORDER NUMBER FOLLOWED BY THE NAME OF THE CUSTOMER WHO MADE THE ORDER.
SELECT ORDERS.ONUM, CUSTOMERS.CNAME
FROM ORDERS, CUSTOMERS
WHERE ORDERS.CNUM = CUSTOMERS.CNUM;

-- Q.2 WRITE A QUERY THAT GIVES THE NAMES OF BOTH THE SALESPERSON AND THE CUSTOMER FOR EACH ORDER ALONG WITH THE ORDER NUMBER.
SELECT SNAME,CNAME,ONUM
FROM ORDERS O,CUSTOMERS C,SALESPEOPLE S
WHERE O.SNUM=C.SNUM AND O.SNUM=S.SNUM;


-- Q.3 WRITE A QUERY THAT PRODUCES ALL CUSTOMERS SERVICED BY SALESPEOPLE WITH A COMMISSION ABOVE 12%.OUTPUT THE CUSTOMER’S NAME, THE SALESPERSON’S NAME, AND THE SALESPERSON’S RATE OF COMMISSION.
SELECT CNAME,
S.SNUM,
COMM*100 "RATE OF COMM."
FROM CUSTOMERS C,
SALESPEOPLE S
WHERE C.SNUM=S.SNUM
AND COMM>.12 ;

-- Q.4 WRITE A QUERY THAT CALCULATES THE AMOUNT OF THE SALESPERSON’S COMMISSION ON EACH ORDER BY A CUSTOMER WITH A RATING ABOVE 100

SELECT SNAME, AMT * COMM
FROM ORDERS, CUSTOMERS, SALESPEOPLE
WHERE RATING > 100 AND
SALESPEOPLE.SNUM = CUSTOMERS.SNUM AND
SALESPEOPLE.SNUM = ORDERS.SNUM AND
CUSTOMERS.CNUM = ORDERS.CNUM

-- Q.5 WRITE A QUERY THAT PRODUCES ALL PAIRS OF SALESPEOPLE WHO ARE LIVING IN THE SAME CITY.EXCLUDE COMBINATIONS OF SALESPEOPLE WITH THEMSELVES AS WELL AS DUPLICATE ROWS WITH THE ORDER REVERSED
SELECT M.SNAME, N.SNAME, M.CITY
FROM SALESPEOPLE M,SALESPEOPLE N
WHERE M.CITY=N.CITY
AND M.SNAME<N.SNAME;
