-- Q.1 WRITE A QUERY THAT COUNTS THE NUMBER OF SALESPEOPLE REGISTERING ORDERS FOR EACH DAY. (IF A SALESPERSON HAS MORE THAN ONE ORDER ON A GIVEN DAY, HE OR SHE SHOULD BE COUNTED ONLY ONCE.)
SELECT ODATE,SNUM,COUNT(*) AS ORDERS FROM ORDERS GROUP BY ODATE,SNUM;

-- Q.2 WRITE A QUERY ON THE CUSTOMERS TABLE THAT WILL FIND THE HIGHEST RATING IN EACH CITY. PUT THE OUTPUT IN THIS FORM:
-- FOR THE CITY (CITY), THE HIGHEST RATING IS : (RATING).
SELECT CITY,MAX(RATING) MAX_RATING FROM CUSTOMERS  GROUP BY CITY;

-- Q.3 WRITE A QUERY THAT TOTALS THE ORDERS FOR EACH DAY AND PLACES THE RESULTS IN DESCENDING ORDER.
SELECT COUNT(ODATE) "TOTAL ORDERS",ODATE FROM ORDERS GROUP BY ODATE ORDER BY "TOTAL ORDERS";

-- Q.4 WRITE A QUERY THAT SELECTS THE TOTAL AMOUNT IN ORDERS FOR EACH SALESPERSON FOR WHOM THIS TOTAL IS GREATER THAN THE AMOUNT OF THE LARGEST ORDER IN THE TABLE.
SELECT SUM(AMT)FROM ORDERS GROUP BY SNUM HAVING SUM(AMT)>(SELECT MAX(AMT) FROM ORDERS);

-- Q.5 WRITE A QUERY THAT SELECTS THE HIGHEST RATING IN EACH CITY.
SELECT CITY,MAX(RATING) AS MAXRATINGINCITY FROM CUSTOMERS GROUP BY CITY;

-- Q.6 LARGEST ORDER TAKEN BY EACH SALESPERSON WITH ORDER VALUE MORE THAN RS.3000. 7. SELECT EACH CUSTOMER SMALLEST ORDER.
SELECT ODATE, SNUM, MAX(AMT) FROM ORDERS WHERE AMT > 3000 GROUP BY ODATE, SNUM ORDER BY ODATE,SNUM;
SELECT CNUM, MIN(AMT) FROM ORDERS GROUP BY CNUM;
