-- Q.1 WRITE A QUERY THAT USES A SUBQUERY TO OBTAIN ALL ORDERS FOR THE CUSTOMER NAMED CISNEROS. ASSUME YOU DO NOT KNOW HIS CUSTOMER NUMBER (CNUM).
SELECT ONUM "ALL ORDERS",
CNUM
FROM ORDERS
WHERE CNUM=
(SELECT CNUM
FROM CUSTOMERS
WHERE CNAME='CISNEROS');

-- Q.2 WRITE A QUERY THAT PRODUCES THE NAMES AND RATINGS OF ALL CUSTOMERS WHO HAVE ABOVE- AVERAGE ORDERS.
SELECT MAX(B.CNAME), MAX(B.RATING), A.CNUM FROM ORDERS A, CUSTOMERS B WHERE A.CNUM = B.CNUM GROUP BY A.CNUM HAVING COUNT(A.CNUM) > ( SELECT AVG(COUNT(CNUM)) FROM ORDERS GROUP BY CNUM);

-- Q.3 WRITE A QUERY THAT SELECTS THE TOTAL AMOUNT IN ORDERS FOR EACH SALESPERSON FOR WHOM THIS TOTAL IS GREATER THAN THE AMOUNT OF THE LARGEST ORDER IN THE TABLE.
SELECT SNUM, SUM(AMT)
FROM ORDERS
GROUP BY SNUM
HAVING SUM(AMT) > ( SELECT MAX(AMT)
FROM ORDERS);

-- Q.4 WRITE A QUERY THAT SELECTS ALL CUSTOMERS WHOSE RATINGS ARE EQUAL TO OR GREATER THAN ANY OF SERIES.
SELECT A.SNAME,B.RATING FROM SALESPEOPLE A,CUSTOMERS B WHERE A.SNUM=B.SNUM;
SELECT * FROM CUSTOMERS WHERE RATING>=200;


-- Q.5 WRITE A QUERY USING ANY OR ALL THAT WILL FIND ALL SALESPEOPLE WHO HAVE NO CUSTOMERS LOCATED IN THEIR CITY.
SELECT A.SNAME,A.CITY,B.CNAME FROM SALESPEOPLE A,CUSTOMERS B WHERE A.CITY=B.CITY;

-- Q.6 WRITE A QUERY THAT SELECTS ALL ORDERS FOR AMOUNTS GREATER THAN ANY FOR THE CUSTOMERS IN LONDON.
SELECT *
FROM ORDERS
WHERE AMT <
(SELECT MAX (AMT)
FROM ORDERS A, CUSTOMERS B
WHERE  A.SNUM=B.SNUM
AND B.CITY='LONDON');

-- Q.7 EXTRACT ALL THE ORDERS OF MOTIKA.
SELECT ONUM
FROM ORDERS
WHERE SNUM = ( SELECT SNUM
FROM SALESPEOPLE
WHERE SNAME = 'MOTIKA');

-- Q.8 FIND ALL THE ORDER ATTRIBUTE TO SALESPEOPLE SERVICING CUSTOMERS IN LONDON.
SELECT SNUM, CNUM
FROM ORDERS
WHERE CNUM IN (SELECT CNUM
FROM CUSTOMERS
WHERE CITY = 'LONDON');

-- Q.9 FIND NAMES AND NUMBERS OF ALL SALESPERSON WHO HAVE MORE THAN ONE CUSTOMER. 10. FIND SALESPEOPLE NUMBER,NAME AND CITY WHO HAVE MULTIPLE CUSTOMERS.
SELECT A.SNUM, A.SNAME
FROM SALESPEOPLE A
WHERE 1 <
(SELECT COUNT(*)
FROM CUSTOMERS
WHERE A.SNUM=A.SNUM);

-- Q.10 SELECT CUSTOMERS WHO HAVE A GREATER RATING THAN ANY OTHER CUSTOMER IN ROME.
SELECT A.CNAME
FROM CUSTOMERS A
WHERE CITY = 'ROME' AND
RATING > ( SELECT MAX(RATING)
FROM CUSTOMERS
WHERE CITY != 'ROME');

-- Q.11 SELECT ALL ORDERS THAT HAD AMOUNTS THAT WERE GREATER THAT AT LEAST ONE OF THE ORDERS FROM ‘1990-10-04’ .
SELECT *
FROM ORDERS
WHERE AMT > ANY (SELECT AMT
FROM ORDERS
WHERE ODATE = '1990-19-04');

-- Q.12 FIND ALL ORDERS WITH AMOUNTS SMALLER THAN ANY AMOUNT FOR A CUSTOMER IN SAN JOSE.
SELECT ONUM, AMT FROM ORDERS WHERE AMT < ANY ( SELECT AMT FROM ORDERS, CUSTOMERS WHERE CITY = 'SAN JOSE' AND ORDERS.CNUM = CUSTOMERS.CNUM);

-- Q.13 SELECT THOSE CUSTOMERS WHOSE RATING ARE HIGHER THAN EVERY CUSTOMER IN PARIS.
SELECT *
FROM CUSTOMERS A
WHERE NOT EXISTS ( SELECT B.RATING
FROM CUSTOMERS B
WHERE B.CITY != 'PARIS' AND
B.RATING > A.RATING);
