-- Q1. DISPLAY FIRST NAME AND LAST NAME AFTER CONVERTING THE FIRST LETTER OF EACH NAME TO UPPER CASE AND THE REST TO LOWER CASE.
SELECT UPPER(SUBSTRING(FIRST_NAME, 1,1))+ LOWER(SUBSTRING(FIRST_NAME, 2, LEN(FIRST_NAME)-1))AS FIRST_NAME ,UPPER(SUBSTRING(LAST_NAME, 1,1))+ LOWER(SUBSTRING(LAST_NAME, 2, LEN(LAST_NAME)-1)) AS LAST_NAME FROM EMPLOYEES;

-- Q.2 DISPLAY THE FIRST WORD IN JOB TITLE.
SELECT SUBSTRING(JOB_TITLE,1,1) AS FIRSTLETTEROFJOB FROM JOBS;

-- Q.3 DISPLAY THE LENGTH OF FIRST NAME FOR EMPLOYEES WHERE LAST NAME CONTAIN CHARACTER ‘B’ AFTER 3RD POSITION.
SELECT FIRST_NAME,LAST_NAME,LEN(FIRST_NAME) AS LENGTH_OF_FIRST_NAME FROM EMPLOYEES WHERE (SUBSTRING(LAST_NAME,4,LEN(LAST_NAME))LIKE 'B%');

-- Q.4 DISPLAY FIRST NAME IN UPPER CASE AND EMAIL ADDRESS IN LOWER CASE FOR EMPLOYEES WHERE THE FIRST NAME AND EMAIL ADDRESS ARE SAME IRRESPECTIVE OF THE CASE.
SELECT UPPER(FIRST_NAME) AS FIRST_NAME_UPPER,LOWER(EMAIL) AS EMAIL_LOWER FROM EMPLOYEES WHERE (UPPER(FIRST_NAME) LIKE LOWER(EMAIL)) OR (LOWER(FIRST_NAME) LIKE UPPER(EMAIL));

-- Q.5 DISPLAY FIRST NAME, SALARY, AND ROUND THE SALARY TO THOUSANDS.
SELECT FIRST_NAME, SALARY, ROUND(SALARY, -3) AS ROUNDED FROM EMPLOYEES;

-- Q.6 DISPLAY EMPLOYEE ID AND THE DATE ON WHICH HE ENDED HIS PREVIOUS JOB.
SELECT EMPLOYEE_ID, MAX(END_DATE) AS LAST_DATE FROM JOB_HISTORY GROUP BY EMPLOYEE_ID;

-- Q.7 DISPLAY FIRST NAME AND DATE OF FIRST SALARY OF THE EMPLOYEES.
SELECT FIRST_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE)+1 FROM EMPLOYEES;

-- Q.8 DISPLAY FIRST NAME AND EXPERIENCE OF THE EMPLOYEES.
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, JOB_ID, CONVERT(VARCHAR(3),DATEDIFF(MONTH, HIRE_DATE, GETDATE())/12) +' YEARS '+ CONVERT(VARCHAR(2),DATEDIFF(MONTH, HIRE_DATE, GETDATE()) % 12)+ ' MONTHS' AS EXPERIENCE FROM EMPLOYEES;

-- Q.9 DISPLAY FIRST NAME OF EMPLOYEES WHO JOINED IN 2001.
SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '2001-01-01' AND '2001-12-12';

-- Q.10 DISPLAY EMPLOYEES WHO JOINED IN THE CURRENT YEAR.
SELECT * FROM EMPLOYEES WHERE YEAR(HIRE_DATE) = YEAR(GETDATE());

-- Q.11 DISPLAY THE NUMBER OF DAYS BETWEEN SYSTEM DATE AND 1ST JANUARY 2011.
SELECT DATEDIFF(DAY, '20110101', GETDATE()) AS TOTAL_DAYS;

-- Q.12 DISPLAY NUMBER OF EMPLOYEES JOINED AFTER 15TH OF THE MONTH.
SELECT * FROM EMPLOYEES WHERE DATEPART(DAY FROM HIRE_DATE) > 15;


-- Q.13 DISPLAY THIRD HIGHEST SALARY OF EMPLOYEES.
WITH RESULT AS (SELECT SALARY,DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSERANK FROM EMPLOYEES)SELECT TOP 1 SALARY FROM RESULT WHERE DENSERANK = 3;