-- Q.1 CREATE 'STUDENT_DB' DATABASE
CREATE DATABASE STUDENT_DB;
use STUDENT_DB;

-- Q.2 CREATE FOLLOWING TABLES IN DATABASE WITH PROPER DATA TYPES
-- STUDENT: ID (PK), NAME, ADDRESS, PHONE, EMAIL, AGE, SCHOOLID (FK)
-- SCHOOL: ID (PK), NAME, ADDRESS, PRINCIPAL, PHONE
CREATE TABLE STUDENT(ID INT PRIMARY KEY IDENTITY(1,1),NAME VARCHAR(20),ADDRESS VARCHAR(40),PHONE VARCHAR(12),EMAIL VARCHAR(25),AGE INT,SCHOOLID INT ,FOREIGN KEY(SCHOOLID) REFERENCES SCHOOL(ID));
CREATE TABLE SCHOOL(ID INT PRIMARY KEY IDENTITY(1,1),NAME VARCHAR(20),ADDRESS VARCHAR(30),PRICIPAL VARCHAR(20),PHONE VARCHAR(12));

-- Q.3 CREATE RELATIONSHIP AS SHOWN IN THE TABLE SCHEMA
DONE

-- Q.4 ADD SOME DUMMY DATA
insert into School(NAME,ADDRESS,PRICIPAL,PHONE) values
('School 6','Vidhya Nagar,Pune','Rahul','6789012345');
INSERT INTO STUDENT(NAME,ADDRESS,PHONE,EMAIL,AGE,SCHOOLID) VALUES
('ABHAY PANCHAL','SHIVAJI CHOWK, NILANGA','9146334963','ABHAYRPANCHAL@GMAIL.COM',26,2),
('SHUBHAM WAGHMARE','ANAND CHOWK, LATUR','9850800961','SHUBHAMWAGHMARE@GMAIL.COM',26,2),
('SHUBHAM PANCHAL','SHIVAJI CHOWK, NILANGA','9767356855','SHUBHAMPANCHAL@GMAIL.COM',24,3),
('PRANAV PANCHAL','ANANDMUNI CHOWK, NILANGA','9146334963','PRANAVPANCHAL@GMAIL.COM',20,2),
('RAJ MISHRA','BUDHH NAGAR, NANDED','9167634683','RAKMISHRA@GMAIL.COM',24,1)
,('SURAJ KUMAR','HATTI CHOWK,PUNE','9147394528','SURAJ123@GMAIL.COM',25,3);