-- Q.1 CREATE AN INDEX THAT WILL ENABLE A USER TO PULL ORDERS FOR ‘1990-10-03’ OUT OF THE ORDERS TABLE QUICKLY.
CREATE INDEX I_DATE ON ORDERS(DATE); 

-- Q.2 IF THE ORDERS TABLE HAS ALREADY BEEN CREATED, HOW CAN YOU FORCE THE ONUM FIELD TO BE UNIQUE (ASSUME ALL CURRENT VALUES ARE UNIQUE)?
EXEC SP_COLUMNS ORDERS;  
ALTER TABLE ORDERS
ADD CONSTRAINT UK_ONUM UNIQUE  (ONUM);

-- Q.3 CREATE AN INDEX THAT WOULD PERMIT SALESPERSON TO RETRIEVE HIS ORDERS.

CREATE INDEX I_DATE ON ORDERS(DATE);

-- Q.4 LET US ASSUME THAT EACH SALESPERSON IS TO HAVE ONLY ONE CUSTOMER OF A GIVEN RATING, AND THAT THIS IS CURRENTLY THE CASE. CREATE AN INDEX THAT ENFORCES IT.
ALTER TABLE CUSTOMERS ALTER COLUMN RATING INT NOT NULL;

-- Q.5 CREATE AN INDEX TO SPEED UP SEARCHING ORDER ON A GIVEN DATE BY GIVEN CUSTOMER
  CREATE INDEX ODATE ON ORDERS(ID ASC);

