-- Q.1 WRITE A QUERY TO GET UNIQUE DEPARTMENT ID FROM EMPLOYEE TABLE.
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- Q.2 WRITE A QUERY TO GET ALL EMPLOYEE DETAILS FROM THE EMPLOYEE TABLE ORDER BY FIRST NAME, DESCENDING.
SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME DESC;

-- Q.3 WRITE A QUERY TO GET THE EMPLOYEE ID, NAMES (FIRST_NAME, LAST_NAME), SALARY IN ASCENDING ORDER OF SALARY.
SELECT EMPLOYEE_ID,FIRST_NAME+' '+LAST_NAME AS NAMES ,SALARY FROM EMPLOYEES ORDER BY SALARY ASC;

-- Q.4 DISPLAY FIRST NAME AND JOIN DATE OF THE EMPLOYEES WHO IS EITHER IT PROGRAMMER OR SALES MAN.
SELECT DISTINCT COUNTRY_ID FROM COUNTRIES;

-- Q.5 DISPLAY DETAILS OF EMPLOYEE WITH ID 150 OR 160.
SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID IN(150,160);

-- Q.6 DISPLAY FIRST NAME, SALARY, COMMISSION PCT, AND HIRE DATE FOR EMPLOYEES WITH SALARY LESS THAN 10000.
SELECT FIRST_NAME, SALARY, COMMISSION_PCT, HIRE_DATE FROM EMPLOYEES WHERE SALARY<10000;

-- Q.7 DISPLAY EMPLOYEES WHERE THE FIRST NAME OR LAST NAME STARTS WITH S.
SELECT *FROM EMPLOYEES WHERE FIRST_NAME LIKE 'S%';

-- Q.8 DISPLAY DETAILS OF JOBS IN THE DESCENDING ORDER OF THE TITLE.
SELECT *FROM JOBS ORDER BY JOB_TITLE DESC;

-- Q.9 DISPLAY DETAILS OF THE EMPLOYEES WHERE COMMISSION PERCENTAGE IS NULL AND SALARY IN THE RANGE 5000 TO 10000 AND DEPARTMENT IS 30.
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL AND SALARY BETWEEN 5000 AND 10000 AND DEPARTMENT_ID=30;

-- Q.10 DISPLAY EMPLOYEES FIRST_NAME,EMAIL WHO ARE WORKING IN “EXECUTIVE” DEPARTMENT.
SELECT FIRST_NAME, EMAIL FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'EXECUTIVE');

-- Q.11 SELECT DISTINCT COUNTRY_ID FROM COUNTRIES;
SELECT DISTINCT COUNTRY_ID FROM COUNTRIES;

-- Q.12 DISPLAY ALL EMPLOYEES WHOSE HAVE JOB_ID IT_PROG AND FI_ACCOUNT.
SELECT *FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG','FI_ACCOUNT');

-- Q.13 DISPLAY ALL COUNTRIES IN ASCENDING ORDER.
SELECT COUNTRY_NAME FROM COUNTRIES ORDER BY COUNTRY_NAME DESC;
